# Generated by Django 5.1.5 on 2025-01-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_year", models.SmallIntegerField(blank=True, null=True)),
                ("death_year", models.SmallIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "books_author",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gutenberg_id", models.IntegerField(unique=True)),
                ("download_count", models.IntegerField(blank=True, null=True)),
                ("media_type", models.CharField(max_length=16)),
                ("title", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "db_table": "books_book",
                "ordering": ["-download_count"],
            },
        ),
        migrations.CreateModel(
            name="Bookshelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "books_bookshelf",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4, unique=True)),
            ],
            options={
                "db_table": "books_language",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "books_subject",
            },
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.author"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "db_table": "books_book_authors",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books", through="books.BookAuthor", to="books.author"
            ),
        ),
        migrations.CreateModel(
            name="BookBookshelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "bookshelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.bookshelf",
                    ),
                ),
            ],
            options={
                "db_table": "books_book_bookshelves",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="bookshelves",
            field=models.ManyToManyField(
                related_name="books",
                through="books.BookBookshelf",
                to="books.bookshelf",
            ),
        ),
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mime_type", models.CharField(max_length=32)),
                ("url", models.CharField(max_length=256)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formats",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "db_table": "books_format",
            },
        ),
        migrations.CreateModel(
            name="BookLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.language"
                    ),
                ),
            ],
            options={
                "db_table": "books_book_languages",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="languages",
            field=models.ManyToManyField(
                related_name="books", through="books.BookLanguage", to="books.language"
            ),
        ),
        migrations.CreateModel(
            name="BookSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.subject"
                    ),
                ),
            ],
            options={
                "db_table": "books_book_subjects",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="subjects",
            field=models.ManyToManyField(
                related_name="books", through="books.BookSubject", to="books.subject"
            ),
        ),
    ]
